name: build

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  KSPBT_GameRoot: /tmp/ksp
  RELEASE_STAGING: /tmp/release
  LMP_VERSION: 0.29.2

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Mod Repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0 # get full history, not shallow clone

      - name: Set version from tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          V="${{ github.ref_name }}"; BASE_VERSION="${V%%-*}"
          [[ "$V" == *-* ]] && echo "PRERELEASE=-p" >> $GITHUB_ENV
          sed -i "s|<AssemblyVersion>.*</AssemblyVersion>|<AssemblyVersion>${BASE_VERSION}</AssemblyVersion>|" BuildConfigurationBase.targets
          sed -i "s|\"VERSION\": \".*\"|\"VERSION\": \"${BASE_VERSION}\"|" lunacompat.version

      - name: Get Changelog Information
        uses: drewcassidy/yaclog@1.5.0
        id: yaclog-show

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/setup-ckan@1.1.1

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@1.1.1
        with:
           dependency-identifiers: Harmony2 LunaMultiplayer=${{ env.LMP_VERSION }}

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/compile@1.1.1
        with:
          ksp-zip-url: https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip

      - name: Generate KSP Changelog
        uses: drewcassidy/yaclog-ksp@1.2.0
        with:
          mod-name: LunaCompat
          output-path: Build/GameData/LunaCompat/lunacompat-version.cfg

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/assemble-release@1.1.1
        id: assemble-release
        with:
          artifacts: Build/GameData
          output-file-name: 'LunaCompat'

      - name: Upload Client Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LunaCompat
          path: ${{ steps.assemble-release.outputs.artifact-dir-path }}

      - name: Download LMP Server
        id: download-lmp-server
        run: |
          URL="https://github.com/LunaMultiplayer/LunaMultiplayer/releases/download/${{ env.LMP_VERSION }}/LunaMultiplayer-Server-Release.zip"
          curl -L -o lmp-server.zip "$URL"
          unzip lmp-server.zip -d lmp-server
          echo "path=$(pwd)/lmp-server/LMPServer" >> $GITHUB_OUTPUT

      - name: Build LunaCompatServerPlugin
        run: dotnet build LunaCompatServerPlugin/LunaCompatServerPlugin.csproj -c Release -p:LMPServerRoot=${{ steps.download-lmp-server.outputs.path }} -p:SolutionDir=${{ github.workspace }}

      - name: Upload Server Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LunaCompatServerPlugin
          path: Build/**/LunaCompatServerPlugin.dll

      - name: Publish to Github
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          mkdir -p /tmp/server_plugin_zip/LunaCompat
          cp $(find Build -name "LunaCompatServerPlugin.dll" | head -n 1) /tmp/server_plugin_zip/LunaCompat/
          (cd /tmp/server_plugin_zip && zip -r ${{ github.workspace }}/LunaCompatServerPlugin.zip LunaCompat)
          (cd ${{ steps.assemble-release.outputs.artifact-dir-path }} && zip -r ${{ github.workspace }}/LunaCompat.zip .)
          gh release create ${{ github.ref_name }} \
            ${{ env.PRERELEASE }} \
            --notes-file "${{ steps.yaclog-show.outputs.body-file }}" \
            --title "${{ steps.yaclog-show.outputs.name }}" \
            LunaCompat.zip \
            LunaCompatServerPlugin.zip \
            Build/GameData/LunaCompat/lunacompat.version
        # We publish both the mod AND the version file, that way there's always a static latest version file to compare against
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

